-- ============================================
-- 五险一金计算器 - Supabase 数据库初始化脚本
-- ============================================
-- 执行方式：
-- 1. 登录 Supabase 控制台 (https://supabase.com/dashboard)
-- 2. 选择你的项目
-- 3. 点击左侧菜单 "SQL Editor"
-- 4. 点击 "New query"
-- 5. 将本文件内容粘贴到编辑器中
-- 6. 点击 "Run" 执行
-- ============================================

-- 1. 创建 cities 表（城市标准表）
CREATE TABLE IF NOT EXISTS cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_name TEXT NOT NULL,
  year TEXT NOT NULL,
  base_min INTEGER NOT NULL,
  base_max INTEGER NOT NULL,
  rate NUMERIC NOT NULL
);

-- 2. 创建 salaries 表（员工工资表）
CREATE TABLE IF NOT EXISTS salaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id TEXT NOT NULL,
  employee_name TEXT NOT NULL,
  month TEXT NOT NULL,
  salary_amount INTEGER NOT NULL
);

-- 3. 创建 results 表（计算结果表）
CREATE TABLE IF NOT EXISTS results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_name TEXT NOT NULL,
  avg_salary NUMERIC NOT NULL,
  contribution_base NUMERIC NOT NULL,
  company_fee NUMERIC NOT NULL
);

-- ============================================
-- 可选：添加索引以提高查询性能
-- ============================================
CREATE INDEX IF NOT EXISTS idx_cities_year ON cities(year);
CREATE INDEX IF NOT EXISTS idx_salaries_employee_name ON salaries(employee_name);
CREATE INDEX IF NOT EXISTS idx_salaries_month ON salaries(month);

-- ============================================
-- 开发环境设置：禁用 RLS（Row Level Security）
-- ============================================
-- 注意：生产环境应该启用 RLS 并配置适当的策略

ALTER TABLE cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE salaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE results ENABLE ROW LEVEL SECURITY;

-- 开发环境：允许所有操作（生产环境请修改）
DROP POLICY IF EXISTS "Enable all access for cities" ON cities;
CREATE POLICY "Enable all access for cities" ON cities
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access for salaries" ON salaries;
CREATE POLICY "Enable all access for salaries" ON salaries
  FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access for results" ON results;
CREATE POLICY "Enable all access for results" ON results
  FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- 验证表是否创建成功
-- ============================================
SELECT 'cities' as table_name, COUNT(*) as row_count FROM cities
UNION ALL
SELECT 'salaries', COUNT(*) FROM salaries
UNION ALL
SELECT 'results', COUNT(*) FROM results;
